# Generated by Django 5.0.1 on 2024-01-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=10)),
                ('city_name', models.CharField(max_length=100)),
                ('city_name_i18n', models.TextField(blank=True, null=True)),
                ('districts_id', models.IntegerField()),
                ('states_id', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountriesLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=64)),
                ('country_code', models.CharField(max_length=2)),
                ('country_isd_code', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.IntegerField()),
                ('is_allowed_sms', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DistrictsLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('district_code', models.CharField(blank=True, max_length=10, null=True)),
                ('district_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatesLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
