# Generated by Django 5.0 on 2024-01-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Guest', 'verbose_name_plural': 'Guests'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
