# Generated by Django 5.0.1 on 2024-01-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awas', '0002_citieslocal_countrieslocal_districtslocal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
    ]
