# Generated by Django 5.0.1 on 2024-01-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awas', '0004_alter_guest_arrival_date_alter_guest_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='awas_incharge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lock_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='transport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
